SUPABASE_URL="https://wyyeucopnwcoiktyupje.supabase.co"
SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5eWV1Y29wbndjb2lrdHl1cGplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzMjU5MDQsImV4cCI6MjA4NTkwMTkwNH0.RbMYBGho8yXACU6S3DKjEJ8HsbAzNINLl7-im-2F0bk"
